### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by ntg28** [ntg28/viewer4reddit#1]
### Html and Css
- [ ] Header
  - [ ] Icon
  - [ ] Subreddit search input
  - [ ] Buttons for hot, new and top
- [ ] Main is for the Reddit content

### Javascript
- [ ] Get the input value
- [ ] Get the Subreddit information
- [ ] Show the Subreddit information
